module.exports = {
  USER_CONNECTED: 'USER_CONNECTED',
  USER_DISCONNECTED: 'USER_DISCONNECTED',
  MESSAGE_RECIEVED: 'MESSAGE_RECIEVED',
  MESSAGE_SENT: 'MESSAGE_SENT',
  TYPING: 'TYPING',
  VERIFY_USER: 'VERIFY_USER',
  LOGOUT: 'LOGOUT',
  NEW_CHAT: 'NEW_CHAT',
  JOIN_CHAT: 'JOIN_CHAT',
  JOINED_CHAT: 'JOINED_CHAT',
  USER_JOINED: 'USER_JOINED',
  STREAM: 'STREAM'
}